### ISSUE TITLE
Warp in browser - webpack compatible

### ISSUE THREAD

**Issue by descampsk** [ScaleDynamics/warp#42]
Hello,

I would be very interested in testing your technology but in a browser for client-side cryptographic operations. 
Feel free to send me a pm if you have a beta to test and you're interested to do some tests.
I use webpack to build the webapp

Thank you in advance! 

Kévin

**Comment by gcabillic** [comment]
Hi Kévin,

Thanks for your interest and your offer to do some testing. Note that our technology is available for the browser and compatible with webpack.

Could you fill the form here https://www.scaledynamics.io/#helpme with your email address so we'll be able to contact you?

Thanks!

**Comment by descampsk** [comment]
Oh nice news ! 
When I asked at Vivatech, it wasn't atm available :).
I fill the form with no website, because our website isn't public yet.
Feel free to contact me anytime.

Thanks.
